"""create resumes, parsed_documents, score_reports tables

Revision ID: 94862807b456
Revises: 
Create Date: 2026-07-24 10:35:49.235236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94862807b456'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_table('parsed_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('normalized_data', sa.JSON(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_parsed_documents_resume_id_resumes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parsed_documents')),
    sa.UniqueConstraint('resume_id', name=op.f('uq_parsed_documents_resume_id'))
    )
    op.create_table('score_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('section_scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_score_reports_resume_id_resumes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_reports'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_reports')
    op.drop_table('parsed_documents')
    op.drop_table('resumes')
    # ### end Alembic commands ###
